networks:
  default:
    name: todo_network

services:
  db:
    image: postgres:18-trixie
    container_name: todo-db2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/db/data:/var/lib/postgresql
    ports:
      - "5433:5432"
    networks:
      - default

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile2
    container_name: todo-php2
    depends_on:
      - db
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./app:/var/www
#    ports:
#      - "5173:5173"
#    healthcheck:
#      test: [ "CMD", "cgi-fcgi", "-bind", "-connect", "127.0.0.1:9000" ]
#      interval: 5s
#      timeout: 3s
#      retries: 5
#    networks:
#      - default

  nginx:
    image: nginx:1.31
    container_name: todo-nginx2
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
#        condition: service_healthy
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www
      - ./docker/nginx/logs:/var/log/nginx
    networks:
      - default